name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: project_configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: project_build
        run: cmake --build build --config Release

      - name: hello_world_test (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          chmod +x build/hello_world
          ./build/hello_world
        shell: bash

      - name: solver_test (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          chmod +x build/solver
          echo "1 -5 6" | ./build/solver
        shell: bash

      - name: hello_world_test (Windows)
        if: matrix.os == 'windows-latest'
        run: .\build\Release\hello_world.exe
        shell: pwsh

      - name: solver_test (Windows)
        if: matrix.os == 'windows-latest'
        run: echo "1 -5 6" | .\build\Release\solver.exe
        shell: pwsh
